# Generated by Django 5.0.7 on 2024-07-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('brand', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
