# Generated by Django 5.0.7 on 2024-07-26 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_carrito_product_inventario_itemcarrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='person',
        ),
        migrations.AddField(
            model_name='carrito',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
