# Generated by Django 5.0.7 on 2024-08-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_product_person_carrito_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
